[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"

[profile.default.optimizer]
enabled = true
runs = 200

# Base Mainnet (Alchemy)
[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/Cts9SUVykfnWx2pW5qWWS"
base_sepolia = "https://sepolia.base.org"

# Etherscan verification
[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# Deployment
[profile.default.fuzz]
runs = 256
